     VERSION   6                                                                
      DESCR   demo of problem with methylergometrin malet refinement            
    HSTRY  1 created readexp.tcl 1.42 Fri Mar 18 12:37:19 PM Central Europe Stan
    HSTRY  2 EXPTOOL  Win32  Mar 18 12:37:40 2005 P P                           
    HSTRY  3 EXPTOOL  Win32  Mar 18 12:37:50 2005 P  A                          
    HSTRY  4 POWPREF Win32  Mar 18 12:37:53 2005                                
    HSTRY  5 EXPTOOL  Win32  Mar 18 12:40:11 2005 P  H                          
    HSTRY  6 POWPREF Win32  Mar 18 12:40:14 2005                                
    HSTRY  7 GENLES  Win32  Mar 18 12:40:24 2005 Sdsq= 0.108E+08 S/E= 0.668E-02 
    HSTRY  8 EXPGUI 1.75 1.42 (3 changes) -- 03/18/05 12:42:16                  
    HSTRY  9 POWPREF Win32  Mar 18 12:42:16 2005                                
    HSTRY 10 GENLES  Win32  Mar 18 12:42:20 2005 Sdsq= 0.601E+07 S/E= 0.440E-02 
    HSTRY 11 EXPGUI 1.75 1.42 (2 changes) -- 03/18/05 12:43:55                  
    HSTRY 12 BKGEDIT 1.42 1.42 -- Fri Mar 18 12:47:00 PM Central Europe Standard
    HSTRY 13 EXPGUI 1.75 1.42 (3 changes) -- 03/18/05 12:47:30                  
    HSTRY 14 POWPREF Win32  Mar 18 12:47:30 2005                                
    HSTRY 15 GENLES  Win32  Mar 18 12:47:35 2005 Sdsq= 0.152E+08 S/E=  15.5     
    HSTRY 16 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:47:46                  
    HSTRY 17 POWPREF Win32  Mar 18 12:47:46 2005                                
    HSTRY 18 GENLES  Win32  Mar 18 12:47:50 2005 Sdsq= 0.341E+07 S/E=  14.0     
    HSTRY 19 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:48:26                  
    HSTRY 20 POWPREF Win32  Mar 18 12:48:26 2005                                
    HSTRY 21 GENLES  Win32  Mar 18 12:48:31 2005 Sdsq= 0.228E+07 S/E=  307.     
    HSTRY 22 POWPREF Win32  Mar 18 12:48:40 2005                                
    HSTRY 23 GENLES  Win32  Mar 18 12:48:47 2005 Sdsq= 0.219E+07 S/E=  1.29     
    HSTRY 24 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:49:01                  
    HSTRY 25 POWPREF Win32  Mar 18 12:49:01 2005                                
    HSTRY 26 GENLES  Win32  Mar 18 12:49:06 2005 Sdsq= 0.213E+07 S/E=  7.96     
    HSTRY 27 POWPREF Win32  Mar 18 12:49:12 2005                                
    HSTRY 28 GENLES  Win32  Mar 18 12:49:17 2005 Sdsq= 0.213E+07 S/E= 0.144E-01 
    HSTRY 29 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:49:25                  
    HSTRY 30 GENLES  Win32  Mar 18 12:49:27 2005 Sdsq= 0.212E+07 S/E= 0.183     
    HSTRY 31 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:49:39                  
    HSTRY 32 GENLES  Win32  Mar 18 12:49:40 2005 Sdsq= 0.210E+07 S/E=  5.53     
    HSTRY 33 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:49:48                  
    HSTRY 34 GENLES  Win32  Mar 18 12:49:49 2005 Sdsq= 0.236E+07 S/E=  80.2     
    HSTRY 35 POWPREF Win32  Mar 18 12:50:02 2005                                
    HSTRY 36 GENLES  Win32  Mar 18 12:50:09 2005 Sdsq= 0.237E+07 S/E=  76.7     
    HSTRY 37 EXPGUI 1.75 1.42 (2 changes) -- 03/18/05 12:50:26                  
    HSTRY 38 POWPREF Win32  Mar 18 12:50:26 2005                                
    HSTRY 39 GENLES  Win32  Mar 18 12:50:32 2005 Sdsq= 0.288E+07 S/E=  517.     
    HSTRY 40 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 12:52:08                  
    HSTRY 41 GENLES  Win32  Mar 18 12:52:11 2005 Sdsq= 0.194E+07 S/E=  289.     
    HSTRY 42 EXPGUI 1.75 1.42 (2 changes) -- 03/18/05 12:52:20                  
    HSTRY 43 POWPREF Win32  Mar 18 12:52:20 2005                                
    HSTRY 44 GENLES  Win32  Mar 18 12:52:26 2005 Sdsq= 0.203E+07 S/E=  40.8     
    HSTRY 45 EXPGUI 1.75 1.42 (2 changes) -- 03/18/05 12:55:04                  
    HSTRY 46 GENLES  Win32  Mar 18 12:55:08 2005 Sdsq= 0.203E+07 S/E=  41.0     
    HSTRY 47 EXPGUI 1.75 1.42 (69 changes) -- 03/18/05 12:58:44                 
    HSTRY 48 GENLES  Win32  Mar 18 12:58:48 2005 Sdsq= 0.182E+07 S/E=  17.4     
    HSTRY 49 EXPGUI 1.75 1.42 (2 changes) -- 03/18/05 13:00:58                  
    HSTRY 50 POWPREF Win32  Mar 18 13:01:00 2005                                
    HSTRY 51 GENLES  Win32  Mar 18 13:01:09 2005 Sdsq= 0.182E+07 S/E=  10.4     
    HSTRY 52 EXPEDT  Win32  Mar 18 13:06:23 2005             L    A             
    HSTRY 53 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 15:00:33                  
    HSTRY 54 POWPREF Win32  Mar 18 15:00:33 2005                                
    HSTRY 55 EXPGUI 1.75 1.42 (1 changes) -- 03/18/05 15:10:20                  
    HSTRY 56 POWPREF Win32  Mar 18 15:12:33 2005                                
    HSTRY 57 GENLES  Win32  Mar 18 15:12:42 2005 Sdsq= 0.183E+07 S/E=  16.6     
    HSTRY 58 POWPREF Win32  Mar 21 14:16:05 2005                                
    HSTRY 59 GENLES  Win32  Mar 21 14:16:11 2005 Sdsq= 0.183E+07 S/E=  10.7     
    HSTRY 60 EXPEDT  Win32  Mar 21 14:16:40 2005 File cleanup only              
    HSTRY 61 EXPEDT  Win32  Mar 21 14:19:30 2005             L    D             
    HSTRY 62 EXPGUI 1.75 1.42 (2 changes) -- 03/21/05 14:19:48                  
    HSTRY 63 GENLES  Win32  Mar 21 14:19:55 2005 Sdsq= 0.183E+07 S/E=  485.     
    HSTRY 64 GENLES  Win32  Mar 21 14:59:31 2005 Sdsq= 0.111E+07 S/E=  376.     
    HSTRY 65 EXPEDT  Win32  Mar 21 15:06:26 2005             L    P             
    HSTRY 66 GENLES  Win32  Mar 21 15:06:49 2005 Sdsq= 0.115E+07 S/E=  125.     
    HSTRY 67 EXPEDT  Win32  Mar 21 15:24:45 2005                   F-EDT        
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  FOUR CDAT1  DELF Z    1 NOPR  0.000                                           
  GNLS  RUN on Mar 21 15:06:51 2005    Total cycles run  83      0.11509E+07    
  GNLS CDAT1  MXCY   5                                                          
  GNLS SHFTS      4.36      0.65                                                
 AFAC  C     2.310020.8439 1.020010.2075 1.5886  .5687  .865051.6512  .2156 RHF 
 AFAC  C_    12.011 .6646       .0035                                           
 AFAC  C_SIZ      1.12      0.92 1.65    3                                      
 AFAC  C_XAB  288.3 170.4 84.13 10.67 7.054 52.30 141.0                         
 AFAC  C_XF1  0.036 0.027 0.018 0.003 0.002 0.049 0.024-0.001-0.001-0.001       
 AFAC  C_XF2  0.021 0.015 0.009 0.002 0.001 0.031 0.012 0.000 0.000 0.000       
 AFAC  N    12.2126  .0057 3.1322 9.8933 2.012528.9975 1.1663  .5826-11.529 RHF 
 AFAC  N_    14.007  .936        1.90                                           
 AFAC  N_SIZ      1.08      0.88 1.55    4 1.30                                 
 AFAC  N_XAB  568.1 337.1 166.1 18.37 11.06 1000. 272.0                         
 AFAC  N_XF1  0.061 0.046 0.031 0.006 0.003 0.081 0.040-0.002-0.002-0.002       
 AFAC  N_XF2  0.042 0.029 0.018 0.003 0.002 0.061 0.025 0.000 0.000 0.000       
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5803      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 EXPR  HTYP1  PXC  RSN  ANG  FLT                                                
 EXPR  NATYP    3                                                               
 EXPR  NHST     4                                                               
 EXPR ATYP 1  N           3      1.08      0.88 1.55    4 1.30                  
 EXPR ATYP 2  O           6      1.09      0.89 1.45   96 1.40                  
 EXPR ATYP 3  C          23      1.12      0.92 1.65    3                       
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  104.9     for  118 variables                     
 REFN RESTR      95 1.14068E+05                                                 
 REFN RPOWD     0.2069    0.1558  10993 1.03683E+06    0.0000    0.0000     0   
 REFN STATS  Cycle  83 There were 11088 observations. Total CHI**2 = 1.1509E+06 
CIF AUTHOR    test1                                                             
CRS1    PNAM  from F:/gsas/MyWork/METMAL_PROBLEMS/SingleCrystallData/ErgMalMonok
CRS1   NATOM   32                                                               
CRS1  ABC     5.711383 12.769679 33.149616    Y    0                            
CRS1  ABCSIG  0.000119  0.000323  0.000971                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG    0.0000    0.0000    0.0000                                      
CRS1  AT  1A  N         0.298093  0.301063  0.802708  1.000000N1         4 000  
CRS1  AT  1B  0.018286                                                    I X   
CRS1  AT  2A  N        -0.242993  0.232921  0.643289  1.000000N2         4 000  
CRS1  AT  2B  0.018286                                                    I X   
CRS1  AT  3A  N        -0.101051 -0.119562  0.586939  1.000000N3         4 000  
CRS1  AT  3B  0.018286                                                    I X   
CRS1  AT  4A  O        -0.392011 -0.089831  0.629440  1.000000O4         4 000  
CRS1  AT  4B  0.018286                                                    I X   
CRS1  AT  5A  O         0.275141 -0.244463  0.621706  1.000000O5         4 000  
CRS1  AT  5B  0.018286                                                    I X   
CRS1  AT  6A  C         0.142269  0.359214  0.777158  1.000000C6         4 000  
CRS1  AT  6B  0.018286                                                    I X   
CRS1  AT  7A  C         0.093889  0.301301  0.743988  1.000000C7         4 000  
CRS1  AT  7B  0.018286                                                    I X   
CRS1  AT  8A  C        -0.041787  0.324595  0.703538  1.000000C8         4 000  
CRS1  AT  8B  0.018286                                                    I X   
CRS1  AT  9A  C        -0.146521  0.216240  0.686963  1.000000C9         4 000  
CRS1  AT  9B  0.018286                                                    I X   
CRS1  AT 10A  C        -0.335838  0.127983  0.625108  1.000000C10        4 000  
CRS1  AT 10B  0.018286                                                    I X   
CRS1  AT 11A  C        -0.132490  0.048875  0.620519  1.000000C11        4 000  
CRS1  AT 11B  0.018286                                                    I X   
CRS1  AT 12A  C         0.000267  0.041778  0.657843  1.000000C12        4 000  
CRS1  AT 12B  0.018286                                                    I X   
CRS1  AT 13A  C         0.028244  0.120984  0.685756  1.000000C13        4 000  
CRS1  AT 13B  0.018286                                                    I X   
CRS1  AT 14A  C         0.216020  0.116118  0.722327  1.000000C14        4 000  
CRS1  AT 14B  0.018286                                                    I X   
CRS1  AT 15A  C         0.355618  0.031303  0.733283  1.000000C15        4 000  
CRS1  AT 15B  0.018286                                                    I X   
CRS1  AT 16A  C         0.490977  0.036291  0.770380  1.000000C16        4 000  
CRS1  AT 16B  0.018286                                                    I X   
CRS1  AT 17A  C         0.476867  0.120605  0.797009  1.000000C17        4 000  
CRS1  AT 17B  0.018286                                                    I X   
CRS1  AT 18A  C         0.342753  0.204512  0.785740  1.000000C18        4 000  
CRS1  AT 18B  0.018286                                                    I X   
CRS1  AT 19A  C         0.217082  0.204610  0.748571  1.000000C19        4 000  
CRS1  AT 19B  0.018286                                                    I X   
CRS1  AT 20A  C        -0.430058  0.312882  0.642232  1.000000C20        4 000  
CRS1  AT 20B  0.018286                                                    I X   
CRS1  AT 21A  C        -0.231092 -0.058417  0.612886  1.000000C21        4 000  
CRS1  AT 21B  0.018286                                                    I X   
CRS1  AT 22A  C        -0.100400 -0.238586  0.588696  1.000000C22        4 000  
CRS1  AT 22B  0.018286                                                    I X   
CRS1  AT 23A  C        -0.213929 -0.279301  0.546848  1.000000C23        4 000  
CRS1  AT 23B  0.018286                                                    I X   
CRS1  AT 24A  C         0.133366 -0.278721  0.590147  1.000000C24        4 000  
CRS1  AT 24B  0.018286                                                    I X   
CRS1  AT 25A  O        -0.341496  0.395460  0.486428  1.000000O125       4 000  
CRS1  AT 25B  0.018286                                                    I X   
CRS1  AT 26A  O        -0.175994  0.503153  0.444832  1.000000O126       4 000  
CRS1  AT 26B  0.018286                                                    I X   
CRS1  AT 27A  O         0.040588  0.314279  0.590238  1.000000O127       4 000  
CRS1  AT 27B  0.018286                                                    I X   
CRS1  AT 28A  O        -0.243001  0.317219  0.546152  1.000000O128       4 000  
CRS1  AT 28B  0.018286                                                    I X   
CRS1  AT 29A  C        -0.161023  0.449172  0.475132  1.000000C129       4 000  
CRS1  AT 29B  0.018286                                                    I X   
CRS1  AT 30A  C         0.054830  0.448636  0.498322  1.000000C130       4 000  
CRS1  AT 30B  0.018286                                                    I X   
CRS1  AT 31A  C         0.104289  0.403656  0.531534  1.000000C131       4 000  
CRS1  AT 31B  0.018286                                                    I X   
CRS1  AT 32A  C        -0.041428  0.342583  0.558545  1.000000C132       4 000  
CRS1  AT 32B  0.018286                                                    I X   
CRS1  CELVOL       2417.685          0.080                                      
CRS1  CHMF 1  N             3.00                                                
CRS1  CHMF 2  O             6.00                                                
CRS1  CHMF 3  C            23.00                                                
CRS1  FMHST1  1                                                                 
CRS1  FMPCTL   28   64  168    0    0    0   28   64  168                       
CRS1  SG SYM  P 21 21 21                                                        
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      3   19   0.01000     YYY YYNY                                   
HAP1 1PRCF 1   0.236196E+03  -0.173472E+02   0.728414E+00   0.000000E+00        
HAP1 1PRCF 2   0.132376E+01   0.210666E+01   0.556495E-02   0.767226E-03        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00                       
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  F:/gsas/MYWORK/METMAL~2/DIFFRA~1/METMAL~1.RAW                     
HST  1  HNAM                                                                    
HST  1  IFIL  F:/gsas/MYWORK/METMAL~2/INSTRU~1/BM01B.ins                        
HST  1 BANK     1                                                               
HST  1 BIGFO   0.387353E+06                                                     
HST  1 CHANS         0         1     11590 105682048     11591    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR    0.6996    0.0000    0.0000               1.000    1     0.      
HST  1 ICONS    0.6996    0.0000    0.0000               1.000    0     0.      
HST  1 IRAD     0                                                               
HST  1 MAXRF   39                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF   638    1.3744    Y    Y                                           
HST  1 R-FAC  638   0.25875   8.483453E+06                                      
HST  1 RPOWD    0.2069    0.1558  10993 1.03683E+06    0.0000    0.0000    0    
HST  1 TRNGE   2.00750  29.48750                                                
HST  1 WREXP    0.0213                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     1   12    Y    0    Y                                           
HST  1BAKGD1   0.961252E+03  -0.181018E+03  -0.114153E+03   0.941202E+02        
HST  1BAKGD2   0.967176E+02  -0.142912E+03   0.133397E+03  -0.100909E+02        
HST  1BAKGD3  -0.676965E+02   0.152906E+02   0.350263E+02  -0.392021E+02        
HST  1CHI       0.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  10.000E+000     2.007                                                
HST  1EXC  2    29.490  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1FFANS1  N            0.000     0.000   NN    0                            
HST  1FFANS2  O            0.000     0.000   NN    0                            
HST  1FFANS3  C            0.000     0.000   NN    0                            
HST  1HSCALE     39.722        Y    0                                           
HST  1I HEAD  ESRF BM01B profile wl 0.69956 2004                                
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1INAME   BM01B                                                             
HST  1MNREF     0    1.3744                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000    Y                                                     
HST  1PHI       0.0000                                                          
HST  1PRCF1     3   19   0.01000                                                
HST  1PRCF11       2.412430      -0.335344       0.256752  0.000000E+000        
HST  1PRCF12       0.689770       0.407357       0.002346       0.000506        
HST  1PRCF13  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF14  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF15  0.000000E+000  0.000000E+000  0.000000E+000                       
HST  1TRMNMX   1.00000   1.00000                                                
HST  2  HNAM  Bond distance restraints                                          
HST  2 FACTR    100.000                                                         
HST  2 NBNDS   36                                                               
HST  2 RMSD    36    0.0434                                                     
HST  2BD0001  1    1    6  1  0  0  0  0 1.393 0.010                            
HST  2BD0002  1    1   18  1  0  0  0  0 1.389 0.010                            
HST  2BD0003  1    2    9  1  0  0  0  0 1.522 0.010                            
HST  2BD0004  1    2   10  1  0  0  0  0 1.498 0.010                            
HST  2BD0005  1    2   20  1  0  0  0  0 1.494 0.010                            
HST  2BD0006  1    3   21  1  0  0  0  0 1.353 0.010                            
HST  2BD0007  1    3   22  1  0  0  0  0 1.461 0.010                            
HST  2BD0008  1    4   21  1  0  0  0  0 1.246 0.010                            
HST  2BD0009  1    5   24  1  0  0  0  0 1.370 0.010                            
HST  2BD000A  1    6    7  1  0  0  0  0 1.369 0.010                            
HST  2BD000B  1    6   19  1  0  0  0  0 2.220 0.010                            
HST  2BD000C  1    7    8  1  0  0  0  0 1.499 0.010                            
HST  2BD000D  1    7   19  1  0  0  0  0 1.399 0.010                            
HST  2BD000E  1    8    9  1  0  0  0  0 1.535 0.010                            
HST  2BD000F  1    9   13  1  0  0  0  0 1.536 0.010                            
HST  2BD0010  1   10   11  1  0  0  0  0 1.519 0.010                            
HST  2BD0011  1   11   12  1  0  0  0  0 1.486 0.010                            
HST  2BD0012  1   11   21  1  0  0  0  0 1.511 0.010                            
HST  2BD0013  1   12   13  1  0  0  0  0 1.339 0.010                            
HST  2BD0014  1   13   14  1  0  0  0  0 1.481 0.010                            
HST  2BD0015  1   14   15  1  0  0  0  0 1.380 0.010                            
HST  2BD0016  1   14   19  1  0  0  0  0 1.391 0.010                            
HST  2BD0017  1   15   16  1  0  0  0  0 1.443 0.010                            
HST  2BD0018  1   16   17  1  0  0  0  0 1.362 0.010                            
HST  2BD0019  1   17   18  1  0  0  0  0 1.364 0.010                            
HST  2BD001A  1   18   19  1  0  0  0  0 1.411 0.010                            
HST  2BD001B  1   22   23  1  0  0  0  0 1.604 0.010                            
HST  2BD001C  1   22   24  1  0  0  0  0 1.461 0.010                            
HST  2BD001D  1   25   26  1  0  0  0  0 2.140 0.010                            
HST  2BD001E  1   25   29  1  0  0  0  0 1.245 0.010                            
HST  2BD001F  1   26   29  1  0  0  0  0 1.242 0.010                            
HST  2BD0020  1   27   32  1  0  0  0  0 1.224 0.010                            
HST  2BD0021  1   28   32  1  0  0  0  0 1.286 0.010                            
HST  2BD0022  1   29   30  1  0  0  0  0 1.436 0.010                            
HST  2BD0023  1   30   31  1  0  0  0  0 1.330 0.010                            
HST  2BD0024  1   31   32  1  0  0  0  0 1.476 0.010                            
HST  3  HNAM  Bond angle restraints                                             
HST  3 FACTR    100.000                                                         
HST  3 NANGS   48                                                               
HST  3 RMSD    48    0.1637                                                     
HST  3AN   1    1    3    109.60      0.10  0006  0001  0012                    
HST  3AN   2    1    3    110.83      0.10  0009  0002  000A                    
HST  3AN   3    1    3    111.83      0.10  0009  0002  0014                    
HST  3AN   4    1    3    109.63      0.10  000A  0002  0014                    
HST  3AN   5    1    3    123.14      0.10  0015  0003  0016                    
HST  3AN   6    1    3    108.85      0.10  0001  0006  0007                    
HST  3AN   7    1    3    133.48      0.10  0006  0007  0008                    
HST  3AN   8    1    3    106.66      0.10  0006  0007  0013                    
HST  3AN   9    1    3    119.59      0.10  0008  0007  0013                    
HST  3AN  10    1    3    108.00      0.10  0007  0008  0009                    
HST  3AN  11    1    3    109.44      0.10  0002  0009  0008                    
HST  3AN  12    1    3    107.75      0.10  0002  0009  000D                    
HST  3AN  13    1    3    115.92      0.10  0008  0009  000D                    
HST  3AN  14    1    3    110.05      0.10  0002  000A  000B                    
HST  3AN  15    1    3    110.72      0.10  000A  000B  000C                    
HST  3AN  16    1    3    109.32      0.10  000A  000B  0015                    
HST  3AN  17    1    3    106.36      0.10  000C  000B  0015                    
HST  3AN  18    1    3    126.30      0.10  000B  000C  000D                    
HST  3AN  19    1    3    120.89      0.10  0009  000D  000C                    
HST  3AN  20    1    3    115.47      0.10  0009  000D  000E                    
HST  3AN  21    1    3    123.43      0.10  000C  000D  000E                    
HST  3AN  22    1    3    127.29      0.10  000D  000E  000F                    
HST  3AN  23    1    3    115.47      0.10  000D  000E  0013                    
HST  3AN  24    1    3    117.25      0.10  000F  000E  0013                    
HST  3AN  25    1    3    119.39      0.10  000E  000F  0010                    
HST  3AN  26    1    3    122.55      0.10  000F  0010  0011                    
HST  3AN  27    1    3    117.57      0.10  0010  0011  0012                    
HST  3AN  28    1    3    133.76      0.10  0001  0012  0011                    
HST  3AN  29    1    3    104.93      0.10  0001  0012  0013                    
HST  3AN  30    1    3    121.13      0.10  0011  0012  0013                    
HST  3AN  31    1    3    128.09      0.10  0007  0013  000E                    
HST  3AN  32    1    3    109.95      0.10  0007  0013  0012                    
HST  3AN  33    1    3    121.95      0.10  000E  0013  0012                    
HST  3AN  34    1    3    122.50      0.10  0003  0015  0004                    
HST  3AN  35    1    3    114.58      0.10  0003  0015  000B                    
HST  3AN  36    1    3    122.85      0.10  0004  0015  000B                    
HST  3AN  37    1    3    106.46      0.10  0003  0016  0017                    
HST  3AN  38    1    3    111.18      0.10  0003  0016  0018                    
HST  3AN  39    1    3    106.61      0.10  0017  0016  0018                    
HST  3AN  40    1    3    117.22      0.10  0005  0018  0016                    
HST  3AN  41    1    3    118.75      0.10  0019  001D  001A                    
HST  3AN  42    1    3    121.33      0.10  0019  001D  001E                    
HST  3AN  43    1    3    119.78      0.10  001A  001D  001E                    
HST  3AN  44    1    3    130.58      0.10  001D  001E  001F                    
HST  3AN  45    1    3    130.68      0.10  001E  001F  0020                    
HST  3AN  46    1    3    123.99      0.10  001B  0020  001C                    
HST  3AN  47    1    3    118.32      0.10  001B  0020  001F                    
HST  3AN  48    1    3    117.31      0.10  001C  0020  001F                    
HST  4  HNAM  Planar group restraints                                           
HST  4 FACTR    100.000                                                         
HST  4 NPLNS    2                                                               
HST  4 RMSD    17    0.0443                                                     
HST  4PL   1    1    8 0.010019001A001B001C001D001E001F0020                     
HST  4PL   2    1    9 0.01000E000F0010001100120013000100060007                 
LNCN   1   1  1ALLUISO  1.0000                                                  
ZZZZZZZZZZZZ  Last EXP file record                                              
 EXPR DELFRL      1887                                                          
