     VERSION   6                                                                
      DESCR   symvastatin_experimentes with restrains weighting scheme          
    HSTRY  1 created readexp.tcl 1.42 Tue May 10 11:23:46 AM Central Europe Dayl
    HSTRY  2 EXPTOOL  Win32  May 10 11:24:08 2005 P P                           
    HSTRY  3 EXPTOOL  Win32  May 10 11:24:28 2005 P  A                          
    HSTRY  4 EXPTOOL  Win32  May 10 11:24:55 2005 P  H                          
    HSTRY  5 POWPREF Win32  May 10 11:25:04 2005                                
    HSTRY  6 GENLES  Win32  May 10 11:25:07 2005 Sdsq= 0.144E+07 S/E=  107.     
    HSTRY  7 EXPGUI 1.75 1.42 (2 changes) -- 05/10/05 11:26:45                  
    HSTRY  8 BKGEDIT 1.42 1.42 -- Tue May 10 11:29:14 AM Central Europe Daylight
    HSTRY  9 EXPGUI 1.75 1.42 (1 changes) -- 05/10/05 11:29:21                  
    HSTRY 10 POWPREF Win32  May 10 11:29:23 2005                                
    HSTRY 11 GENLES  Win32  May 10 11:29:27 2005 Sdsq= 0.501E+06 S/E= 0.900E-04 
    HSTRY 12 EXPGUI 1.75 1.42 (1 changes) -- 05/10/05 11:30:12                  
    HSTRY 13 EXPGUI 1.75 1.42 (2 changes) -- 05/10/05 11:31:13                  
    HSTRY 14 GENLES  Win32  May 10 11:31:14 2005 Sdsq= 0.308E+06 S/E=  127.     
    HSTRY 15 EXPGUI 1.75 1.42 (2 changes) -- 05/10/05 11:32:36                  
    HSTRY 16 POWPREF Win32  May 10 11:32:37 2005                                
    HSTRY 17 GENLES  Win32  May 10 11:32:41 2005 Sdsq= 0.238E+06 S/E= 0.828     
    HSTRY 18 EXPGUI 1.75 1.42 (2 changes) -- 05/10/05 11:33:36                  
    HSTRY 19 EXPGUI 1.75 1.42 (1 changes) -- 05/10/05 11:33:51                  
    HSTRY 20 GENLES  Win32  May 10 11:33:52 2005 Sdsq= 0.238E+06 S/E= 0.326E-02 
    HSTRY 21 EXPGUI 1.75 1.42 (2 changes) -- 05/10/05 14:29:52                  
    HSTRY 22 POWPREF Win32  May 10 14:29:53 2005                                
    HSTRY 23 EXPEDT  Win32  May 10 14:30:47 2005                   F-EDT        
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  FOUR CDAT1  DELF Z    1 NOPR  0.000                                           
  GNLS  RUN on May 10 11:33:52 2005    Total cycles run  13      0.23840E+06    
  GNLS CDAT1  MXCY  3                                                           
  GNLS SHFTS      0.04      0.01                                                
 AFAC  C     2.310020.8439 1.020010.2075 1.5886  .5687  .865051.6512  .2156 RHF 
 AFAC  C_    12.011 .6646       .0035                                           
 AFAC  C_SIZ      1.12      0.92 1.65    3                                      
 AFAC  C_XAB  288.3 170.4 84.13 10.67 7.054 52.30 141.0                         
 AFAC  C_XF1  0.036 0.027 0.018 0.003 0.002 0.049 0.024-0.001-0.001-0.001       
 AFAC  C_XF2  0.021 0.015 0.009 0.002 0.001 0.031 0.012 0.000 0.000 0.000       
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5803      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 EXPR  HTYP1  PXC                                                               
 EXPR  NATYP    2                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  O           5      1.09      0.89 1.45   96 1.40                  
 EXPR ATYP 2  C          23      1.12      0.92 1.65    3                       
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  24.49     for   18 variables                     
 REFN RPOWD     0.1636    0.1143   9754 2.38402E+05    0.0000    0.0000     0   
 REFN STATS  Cycle  13 There were  9754 observations. Total CHI**2 = 2.3840E+05 
CIF AUTHOR    MH                                                                
CRS1    PNAM  from F:/gsas/MyWork/Simva_Weight/FIXED_molecule/Data/SYMVA_RES_NO_
CRS1   NATOM   28                                                               
CRS1  ABC     6.125657 17.316381 22.468809    Y    0                            
CRS1  ABCSIG  0.000075  0.000267  0.000263                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG    0.0000    0.0000    0.0000                                      
CRS1  AT  1A  O        -0.058500 -0.115800  0.949460  1.000000O1         4 000  
CRS1  AT  1B  0.048565                                                    I     
CRS1  AT  2A  O        -0.299200 -0.160510  1.011240  1.000000O2         4 000  
CRS1  AT  2B  0.048565                                                    I     
CRS1  AT  3A  O        -0.233000 -0.211000  0.827310  1.000000O3         4 000  
CRS1  AT  3B  0.048565                                                    I     
CRS1  AT  4A  O         0.509100  0.123940  0.820700  1.000000O4         4 000  
CRS1  AT  4B  0.048565                                                    I     
CRS1  AT  5A  O         0.272800  0.149700  0.748170  1.000000O5         4 000  
CRS1  AT  5B  0.048565                                                    I     
CRS1  AT  6A  C         0.463800  0.052500  0.932600  1.000000C1A        4 000  
CRS1  AT  6B  0.048565                                                    I     
CRS1  AT  7A  C        -0.198600 -0.171750  0.965630  1.000000C1B        4 000  
CRS1  AT  7B  0.048565                                                    I     
CRS1  AT  8A  C        -0.215300 -0.244300  0.931700  1.000000C2         4 000  
CRS1  AT  8B  0.048565                                                    I     
CRS1  AT  9A  C        -0.102400 -0.246300  0.872650  1.000000C3         4 000  
CRS1  AT  9B  0.048565                                                    I     
CRS1  AT 10A  C         0.111000 -0.203500  0.877520  1.000000C4         4 000  
CRS1  AT 10B  0.048565                                                    I     
CRS1  AT 11A  C         0.075000 -0.120860  0.895870  1.000000C5         4 000  
CRS1  AT 11B  0.048565                                                    I     
CRS1  AT 12A  C         0.282200 -0.077390  0.909970  1.000000C6         4 000  
CRS1  AT 12B  0.048565                                                    I     
CRS1  AT 13A  C         0.254300  0.010290  0.912380  1.000000C7         4 000  
CRS1  AT 13B  0.048565                                                    I     
CRS1  AT 14A  C         0.374700  0.166740  0.863160  1.000000C8         4 000  
CRS1  AT 14B  0.048565                                                    I     
CRS1  AT 15A  C         0.397900  0.253730  0.854760  1.000000C9         4 000  
CRS1  AT 15B  0.048565                                                    I     
CRS1  AT 16A  C         0.628200  0.284600  0.865410  1.000000C10        4 000  
CRS1  AT 16B  0.048565                                                    I     
CRS1  AT 17A  C         0.737300  0.243280  0.915520  1.000000C11        4 000  
CRS1  AT 17B  0.048565                                                    I     
CRS1  AT 18A  C         0.662000  0.179780  0.942360  1.000000C12        4 000  
CRS1  AT 18B  0.048565                                                    I     
CRS1  AT 19A  C         0.781300  0.144400  0.991530  1.000000C13        4 000  
CRS1  AT 19B  0.048565                                                    I     
CRS1  AT 20A  C         0.721800  0.079900  1.016570  1.000000C14        4 000  
CRS1  AT 20B  0.048565                                                    I     
CRS1  AT 21A  C         0.531400  0.030940  0.996560  1.000000C15        4 000  
CRS1  AT 21B  0.048565                                                    I     
CRS1  AT 22A  C         0.447500  0.141470  0.924630  1.000000C17        4 000  
CRS1  AT 22B  0.048565                                                    I     
CRS1  AT 23A  C         0.347300  0.035800  1.042750  1.000000C18        4 000  
CRS1  AT 23B  0.048565                                                    I     
CRS1  AT 24A  C         0.774100  0.281800  0.809500  1.000000C19        4 000  
CRS1  AT 24B  0.048565                                                    I     
CRS1  AT 25A  C         0.435400  0.116100  0.765600  1.000000C20        4 000  
CRS1  AT 25B  0.048565                                                    I     
CRS1  AT 26A  C         0.570200  0.062300  0.728250  1.000000C21        4 000  
CRS1  AT 26B  0.048565                                                    I     
CRS1  AT 27A  C         0.706900  0.013300  0.761500  1.000000C22        4 000  
CRS1  AT 27B  0.048565                                                    I     
CRS1  AT 28A  C         0.797700 -0.052500  0.720900  1.000000C23        4 000  
CRS1  AT 28B  0.048565                                                    I     
CRS1  CELVOL       2383.361          0.032                                      
CRS1  CHMF 1  O             5.00                                                
CRS1  CHMF 2  C            25.00                                                
CRS1  FMHST1  1                                                                 
CRS1  FMPCTL   32   88  112    0    0    0   32   88  112                       
CRS1  SG SYM  P 21 21 21                                                        
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      3   19   0.01000         NN                                     
HAP1 1PRCF 1   0.241243E+01  -0.335344E+00   0.256752E+00   0.000000E+00        
HAP1 1PRCF 2   0.830125E+00   0.454889E+01   0.234600E-02   0.506000E-03        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00                       
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  F:/gsas/MYWORK/SIMVA_~1/FIXED_~1/DATA/SIMVA_~1.RAW                
HST  1  HNAM                                                                    
HST  1  IFIL  F:/gsas/MYWORK/INSTUM~1/BM01B.ins                                 
HST  1 BANK     1                                                               
HST  1 BIGFO   0.967417E+05                                                     
HST  1 CHANS         0         1     10791  51595776     10792    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR    0.6996    0.0000    0.0000               0.950    1     0.      
HST  1 ICONS    0.6996    0.0000    0.0000               0.950    1     0.      
HST  1 IRAD     0                                                               
HST  1 MAXRF   21                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF   504    1.4721                                                     
HST  1 R-FAC  502   0.23449   4.285233E+05                                      
HST  1 RPOWD    0.1636    0.1143   9754 2.38402E+05    0.0000    0.0000    0    
HST  1 TRNGE   3.10750  27.49000                                                
HST  1 WREXP    0.0331                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     1   14    Y    0    Y                                           
HST  1BAKGD1   0.567925E+03  -0.232168E+03  -0.204966E+02   0.549026E+02        
HST  1BAKGD2   0.101699E+02  -0.612954E+02   0.832317E+02  -0.213790E+02        
HST  1BAKGD3  -0.305014E+02   0.181795E+02  -0.256461E+01  -0.182159E+02        
HST  1BAKGD4   0.261713E+02  -0.132188E+02                                      
HST  1CHI       0.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  10.000E+000     3.107                                                
HST  1EXC  2    27.493  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1FFANS1  O            0.000     0.000   NN    0                            
HST  1FFANS2  C            0.000     0.000   NN    0                            
HST  1HSCALE     3.4543        Y    0                                           
HST  1I HEAD  ESRF BM01B profile wl 0.69956 2004                                
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1INAME   BM01B                                                             
HST  1MNREF     0    1.4721                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000    Y                                                     
HST  1PHI       0.0000                                                          
HST  1PRCF1     3   19   0.01000                                                
HST  1PRCF11       2.412430      -0.335344       0.256752  0.000000E+000        
HST  1PRCF12       0.689770       0.407357       0.002346       0.000506        
HST  1PRCF13  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF14  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF15  0.000000E+000  0.000000E+000  0.000000E+000                       
HST  1TRMNMX   1.00000   1.00000                                                
LNCN   1   1  1ALLUISO  1.0000                                                  
ZZZZZZZZZZZZ  Last EXP file record                                              
 EXPR DELFRL      2939                                                          
