     VERSION   6                                                                
      DESCR                                                                     
    HSTRY  1 created readexp.tcl 1.42 Wed Feb 02 2:19:09 PM Central Europe Stand
    HSTRY  2 EXPTOOL  Win32  Feb 02 14:19:32 2005 P P                           
    HSTRY  3 EXPTOOL  Win32  Feb 02 14:19:46 2005 P  A                          
    HSTRY  4 EXPTOOL  Win32  Feb 02 14:20:43 2005 P  H                          
    HSTRY  5 EXPGUI 1.75 1.42 (2 changes) -- 02/02/05 14:20:56                  
    HSTRY  6 POWPREF Win32  Feb 02 14:20:56 2005                                
    HSTRY  7 GENLES  Win32  Feb 02 14:21:01 2005 Sdsq= 0.950E+07 S/E= 0.171E-04 
    HSTRY  8 EXPGUI 1.75 1.42 (3 changes) -- 02/02/05 14:21:29                  
    HSTRY  9 BKGEDIT 1.42 1.42 -- Wed Feb 02 2:25:53 PM Central Europe Standard 
    HSTRY 10 EXPGUI 1.75 1.42 (3 changes) -- 02/02/05 14:26:08                  
    HSTRY 11 POWPREF Win32  Feb 02 14:26:10 2005                                
    HSTRY 12 GENLES  Win32  Feb 02 14:26:12 2005 Sdsq= 0.449E+07 S/E= 0.690E-08 
    HSTRY 13 EXPGUI 1.75 1.42 (2 changes) -- 02/02/05 14:26:38                  
    HSTRY 14 GENLES  Win32  Feb 02 14:26:40 2005 Sdsq= 0.361E+07 S/E=  86.6     
    HSTRY 15 POWPREF Win32  Feb 02 15:03:53 2005                                
    HSTRY 16 GENLES  Win32  Feb 02 15:03:59 2005 Sdsq= 0.358E+07 S/E=  1.42     
    HSTRY 17 EXPGUI 1.75 1.42 (1 changes) -- 02/02/05 15:04:19                  
    HSTRY 18 GENLES  Win32  Feb 02 15:04:21 2005 Sdsq= 0.153E+07 S/E=  36.8     
    HSTRY 19 EXPGUI 1.75 1.42 (1 changes) -- 02/02/05 15:04:39                  
    HSTRY 20 GENLES  Win32  Feb 02 15:04:41 2005 Sdsq= 0.133E+07 S/E=  41.5     
    HSTRY 21 EXPGUI 1.75 1.42 (5 changes) -- 02/02/05 15:05:01                  
    HSTRY 22 GENLES  Win32  Feb 02 15:05:03 2005 Sdsq= 0.127E+07 S/E=  118.     
    HSTRY 23 EXPGUI 1.75 1.42 (1 changes) -- 02/02/05 15:05:21                  
    HSTRY 24 GENLES  Win32  Feb 02 15:05:23 2005 Sdsq= 0.758E+06 S/E=  48.1     
    HSTRY 25 EXPGUI 1.75 1.42 (1 changes) -- 02/02/05 15:06:31                  
    HSTRY 26 EXPGUI 1.75 1.42 (1 changes) -- 02/02/05 15:08:20                  
    HSTRY 27 GENLES  Win32  Feb 02 15:08:22 2005 Sdsq= 0.743E+06 S/E=  11.4     
    HSTRY 28 EXPGUI 1.75 1.42 (2 changes) -- 02/02/05 15:12:07                  
    HSTRY 29 POWPREF Win32  Feb 02 15:12:08 2005                                
    HSTRY 30 GENLES  Win32  Feb 02 15:12:17 2005 Sdsq= 0.730E+06 S/E=  6.43     
    HSTRY 31 EXPEDT  Win32  Feb 02 15:21:28 2005                   F-EDT        
    HSTRY 32 GENLES  Win32  Feb 02 15:21:38 2005 Sdsq= 0.728E+06 S/E=  4.20     
    HSTRY 33 EXPEDT  Win32  Feb 02 16:17:48 2005                   F-EDT        
    HSTRY 34 EXPEDT  Win32  Feb 03 14:53:54 2005                   F-EDT        
    HSTRY 35 EXPEDT  Win32  Feb 03 14:58:58 2005                   F-EDT        
    HSTRY 36 GENLES  Win32  Mar 02 11:05:45 2005 Sdsq= 0.727E+06 S/E=  4.09     
    HSTRY 37 GENLES  Win32  Mar 08 13:56:49 2005 Sdsq= 0.727E+06 S/E=  4.07     
    HSTRY 38 EXPEDT  Win32  Mar 30 12:40:36 2005                   F-EDT        
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  FOUR CDAT1  DELF X    1 NOPR  0.000                                           
  FOUR CDAT2  FOBS X    1 NOPR  0.000                                           
  FOUR CDAT3  FCLC X    1 NOPR  0.000                                           
  FOUR CDAT4  2FDF X    1 NOPR  0.000                                           
  GNLS  RUN on Mar 08 13:56:50 2005    Total cycles run  37      0.72741E+06    
  GNLS CDAT1  MXCY  3                                                           
  GNLS SHFTS      2.02      0.06                                                
 AFAC  C     2.310020.8439 1.020010.2075 1.5886  .5687  .865051.6512  .2156 RHF 
 AFAC  C_    12.011 .6646       .0035                                           
 AFAC  C_SIZ      1.12      0.92 1.65    3                                      
 AFAC  C_XAB  288.3 170.4 84.13 10.67 7.054 52.30 141.0                         
 AFAC  C_XF1  0.036 0.027 0.018 0.003 0.002 0.049 0.024-0.001-0.001-0.001       
 AFAC  C_XF2  0.021 0.015 0.009 0.002 0.001 0.031 0.012 0.000 0.000 0.000       
 AFAC  N    12.2126  .0057 3.1322 9.8933 2.012528.9975 1.1663  .5826-11.529 RHF 
 AFAC  N_    14.007  .936        1.90                                           
 AFAC  N_SIZ      1.08      0.88 1.55    4 1.30                                 
 AFAC  N_XAB  568.1 337.1 166.1 18.37 11.06 1000. 272.0                         
 AFAC  N_XF1  0.061 0.046 0.031 0.006 0.003 0.081 0.040-0.002-0.002-0.002       
 AFAC  N_XF2  0.042 0.029 0.018 0.003 0.002 0.061 0.025 0.000 0.000 0.000       
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5803      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 EXPR  HTYP1  PXC                                                               
 EXPR  NATYP    3                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  N           3      1.08      0.88 1.55    4 1.30                  
 EXPR ATYP 2  O           6      1.09      0.89 1.45   96 1.40                  
 EXPR ATYP 3  C          23      1.12      0.92 1.65    3                       
 EXPR DELFRL      2552                                                          
 EXPR FOBSRL      2552                                                          
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  62.95     for   35 variables                     
 REFN RPOWD     0.1654    0.1213  11590 7.27415E+05    0.0000    0.0000     0   
 REFN STATS  Cycle  37 There were 11590 observations. Total CHI**2 = 7.2741E+05 
CRS1    PNAM  from F:/gsas/MyWork/METMAL_NOMET/MetMal_FOX18.cif                 
CRS1   NATOM   32                                                               
CRS1  ABC    12.769237 33.148277  5.711365    Y    0                            
CRS1  ABCSIG  0.000240  0.000696  0.000086                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG    0.0000    0.0000    0.0000                                      
CRS1  AT  1A  N         0.193000  0.295500  0.170000  1.000000N1         4 000  
CRS1  AT  1B  0.014925                                                    I  U  
CRS1  AT  2A  N         0.277800  0.144700  0.771800  1.000000N2         4 000  
CRS1  AT  2B  0.014925                                                    I  U  
CRS1  AT  3A  N         0.626700  0.089200  0.586600  1.000000N3         4 000  
CRS1  AT  3B  0.014925                                                    I  U  
CRS1  AT  4A  O         0.588400  0.125900  0.852400  1.000000O4         4 000  
CRS1  AT  4B  0.014925                                                    I  U  
CRS1  AT  5A  O         0.749800  0.123700  0.226100  1.000000O5         4 000  
CRS1  AT  5B  0.014925                                                    I  U  
CRS1  AT  6A  C         0.138200  0.277400  0.371400  1.000000C6         4 000  
CRS1  AT  6B  0.014925                                                    I  U  
CRS1  AT  7A  C         0.176000  0.241900  0.385400  1.000000C7         4 000  
CRS1  AT  7B  0.014925                                                    I  U  
CRS1  AT  8A  C         0.170600  0.204200  0.565000  1.000000C8         4 000  
CRS1  AT  8B  0.014925                                                    I  U  
CRS1  AT  9A  C         0.287400  0.184000  0.644900  1.000000C9         4 000  
CRS1  AT  9B  0.014925                                                    I  U  
CRS1  AT 10A  C         0.364800  0.126400  0.844500  1.000000C10        4 000  
CRS1  AT 10B  0.014925                                                    I  U  
CRS1  AT 11A  C         0.453500  0.121200  0.661200  1.000000C11        4 000  
CRS1  AT 11B  0.014925                                                    I  U  
CRS1  AT 12A  C         0.467100  0.153800  0.508200  1.000000C12        4 000  
CRS1  AT 12B  0.014925                                                    I  U  
CRS1  AT 13A  C         0.375900  0.184400  0.473200  1.000000C13        4 000  
CRS1  AT 13B  0.014925                                                    I  U  
CRS1  AT 14A  C         0.375700  0.224600  0.292000  1.000000C14        4 000  
CRS1  AT 14B  0.014925                                                    I  U  
CRS1  AT 15A  C         0.460100  0.234500  0.146300  1.000000C15        4 000  
CRS1  AT 15B  0.014925                                                    I  U  
CRS1  AT 16A  C         0.465000  0.263400 -0.006500  1.000000C16        4 000  
CRS1  AT 16B  0.014925                                                    I  U  
CRS1  AT 17A  C         0.371700  0.294800  0.036700  1.000000C17        4 000  
CRS1  AT 17B  0.014925                                                    I  U  
CRS1  AT 18A  C         0.287000  0.287700  0.177500  1.000000C18        4 000  
CRS1  AT 18B  0.014925                                                    I  U  
CRS1  AT 19A  C         0.284500  0.251100  0.295200  1.000000C19        4 000  
CRS1  AT 19B  0.014925                                                    I  U  
CRS1  AT 20A  C         0.186600  0.145400  0.914500  1.000000C20        4 000  
CRS1  AT 20B  0.014925                                                    I  U  
CRS1  AT 21A  C         0.552400  0.107600  0.710000  1.000000C21        4 000  
CRS1  AT 21B  0.014925                                                    I  U  
CRS1  AT 22A  C         0.734000  0.085800  0.607400  1.000000C22        4 000  
CRS1  AT 22B  0.014925                                                    I  U  
CRS1  AT 23A  C         0.804400  0.052600  0.735700  1.000000C23        4 000  
CRS1  AT 23B  0.014925                                                    I  U  
CRS1  AT 24A  C         0.772500  0.086400  0.383600  1.000000C24        4 000  
CRS1  AT 24B  0.014925                                                    I  U  
CRS1  AT 25A  O         0.685500  0.450100  0.275000  1.000000O1         4 000  
CRS1  AT 25B  0.014925                                                    I  U  
CRS1  AT 26A  O         0.673500  0.404200  0.519200  1.000000O2         4 000  
CRS1  AT 26B  0.014925                                                    I  U  
CRS1  AT 27A  O         0.491300  0.552800  0.327300  1.000000O3         4 000  
CRS1  AT 27B  0.014925                                                    I  U  
CRS1  AT 28A  O         0.615400  0.515200  0.154600  1.000000O4         4 000  
CRS1  AT 28B  0.014925                                                    I  U  
CRS1  AT 29A  C         0.646500  0.439300  0.452100  1.000000C5         4 000  
CRS1  AT 29B  0.014925                                                    I  U  
CRS1  AT 30A  C         0.600200  0.469700  0.613400  1.000000C6         4 000  
CRS1  AT 30B  0.014925                                                    I  U  
CRS1  AT 31A  C         0.566800  0.503100  0.567500  1.000000C7         4 000  
CRS1  AT 31B  0.014925                                                    I  U  
CRS1  AT 32A  C         0.550900  0.523100  0.333400  1.000000C8         4 000  
CRS1  AT 32B  0.014925                                                    I  U  
CRS1  CELVOL       2417.496          0.059                                      
CRS1  CHMF 1  N             3.00                                                
CRS1  CHMF 2  O             6.00                                                
CRS1  CHMF 3  C            23.00                                                
CRS1  FMHST1  1                                                                 
CRS1  FMPCTL   64  168   28    0    0    0   64   84   29                       
CRS1  SG SYM  P 21 21 21                                                        
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      2   18   0.01000     YYYYY Y                                    
HAP1 1PRCF 1   0.247404E+03  -0.147024E+02   0.470081E+00   0.143409E+01        
HAP1 1PRCF 2   0.000000E+00   0.000000E+00   0.143424E+00   0.000000E+00        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00                                      
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  F:/gsas/MYWORK/METMAL/DATA/METMAL~1.RAW                           
HST  1  HNAM                                                                    
HST  1  IFIL  F:/gsas/MYWORK/METMAL/BM01.ins                                    
HST  1 BANK     1                                                               
HST  1 BIGFO   0.387263E+06                                                     
HST  1 CHANS         0         1     11590 105682048     11591    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR    0.6996    0.0000    0.0000               1.000    2     0.      
HST  1 ICONS    0.6996    0.0000    0.0000               1.000    0     0.      
HST  1 IRAD     0                                                               
HST  1 MAXRF   39                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF   638    1.3744    Y    Y                                           
HST  1 R-FAC  638   0.19587   6.526219E+06                                      
HST  1 RPOWD    0.1654    0.1213  11590 7.27415E+05    0.0000    0.0000    0    
HST  1 TRNGE   0.51500  29.48750                                                
HST  1 WREXP    0.0209                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     1   24    Y    0    Y                                           
HST  1BAKGD1   0.184325E+04  -0.193921E+04   0.158407E+04  -0.156035E+04        
HST  1BAKGD2   0.164497E+04  -0.149639E+04   0.132250E+04  -0.103302E+04        
HST  1BAKGD3   0.892493E+03  -0.859302E+03   0.781076E+03  -0.648090E+03        
HST  1BAKGD4   0.514523E+03  -0.436102E+03   0.389965E+03  -0.309297E+03        
HST  1BAKGD5   0.287305E+03  -0.195314E+03   0.146895E+03  -0.147184E+03        
HST  1BAKGD6   0.980225E+02  -0.668793E+02   0.409352E+02  -0.226138E+02        
HST  1CHI       0.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  1     0.000     0.000                                                
HST  1EXC  2    29.490  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1FFANS1  N            0.000     0.000   NN    0                            
HST  1FFANS2  O            0.000     0.000   NN    0                            
HST  1FFANS3  C            0.000     0.000   NN    0                            
HST  1HSCALE     39.630        Y    0                                           
HST  1I HEAD  ESRF BM01B profile wl 0.69956 2004                                
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1INAME   BM01B                                                             
HST  1MNREF     0    1.3744                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000    Y                                                     
HST  1PHI       0.0000                                                          
HST  1PRCF1     2   18   0.01000                                                
HST  1PRCF11  0.000000E+000  0.000000E+000     100.000000  0.000000E+000        
HST  1PRCF12  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF13  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF14  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF15  0.000000E+000  0.000000E+000                                      
HST  1TRMNMX   1.00000   1.00000                                                
LNCN   1   1  1ALLUISO  1.0000                                                  
ZZZZZZZZZZZZ  Last EXP file record                                              
 EXPR FCLCRL      2552                                                          
 EXPR 2FDFRL      2552                                                          
