     VERSION   6                                                                
      DESCR   ergometrin maleat single crystal input                            
    HSTRY  1 created readexp.tcl 1.42 Thu Feb 10 1:59:15 PM Central Europe Stand
    HSTRY  2 EXPTOOL  Win32  Feb 10 13:59:38 2005 P P                           
    HSTRY  3 EXPTOOL  Win32  Feb 10 14:00:03 2005 P  A                          
    HSTRY  4 EXPTOOL  Win32  Feb 10 14:00:29 2005 P  H                          
    HSTRY  5 POWPREF Win32  Feb 10 14:00:31 2005                                
    HSTRY  6 GENLES  Win32  Feb 10 14:00:37 2005 Sdsq= 0.108E+08 S/E= 0.668E-02 
    HSTRY  7 EXPGUI 1.75 1.42 (6 changes) -- 02/10/05 14:01:34                  
    HSTRY  8 EXPGUI 1.75 1.42 (2 changes) -- 02/10/05 14:02:45                  
    HSTRY  9 POWPREF Win32  Feb 10 14:02:53 2005                                
    HSTRY 10 GENLES  Win32  Feb 10 14:02:57 2005 Sdsq= 0.927E+07 S/E= 0.873E-06 
    HSTRY 11 BKGEDIT 1.42 1.42 -- Thu Feb 10 2:05:11 PM Central Europe Standard 
    HSTRY 12 EXPGUI 1.75 1.42 (3 changes) -- 02/10/05 14:07:38                  
    HSTRY 13 POWPREF Win32  Feb 10 14:07:38 2005                                
    HSTRY 14 GENLES  Win32  Feb 10 14:07:41 2005 Sdsq= 0.439E+07 S/E= 0.808E-06 
    HSTRY 15 EXPGUI 1.75 1.42 (3 changes) -- 02/10/05 14:08:17                  
    HSTRY 16 GENLES  Win32  Feb 10 14:08:18 2005 Sdsq= 0.335E+07 S/E= 0.277     
    HSTRY 17 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 14:08:25                  
    HSTRY 18 GENLES  Win32  Feb 10 14:08:26 2005 Sdsq= 0.320E+07 S/E=  4.01     
    HSTRY 19 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 14:08:36                  
    HSTRY 20 GENLES  Win32  Feb 10 14:08:37 2005 Sdsq= 0.216E+07 S/E=  13.4     
    HSTRY 21 EXPGUI 1.75 1.42 (2 changes) -- 02/10/05 14:08:50                  
    HSTRY 22 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 14:09:00                  
    HSTRY 23 GENLES  Win32  Feb 10 14:09:01 2005 Sdsq= 0.234E+07 S/E=  68.2     
    HSTRY 24 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 14:09:08                  
    HSTRY 25 GENLES  Win32  Feb 10 14:09:09 2005 Sdsq= 0.231E+07 S/E=  160.     
    HSTRY 26 EXPGUI 1.75 1.42 (2 changes) -- 02/10/05 14:09:15                  
    HSTRY 27 GENLES  Win32  Feb 10 14:09:16 2005 Sdsq= 0.210E+07 S/E=  42.7     
    HSTRY 28 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 14:09:32                  
    HSTRY 29 GENLES  Win32  Feb 10 14:09:33 2005 Sdsq= 0.212E+07 S/E=  38.3     
    HSTRY 30 GENLES  Win32  Feb 10 14:09:39 2005 Sdsq= 0.211E+07 S/E=  38.4     
    HSTRY 31 EXPGUI 1.75 1.42 (2 changes) -- 02/10/05 14:09:52                  
    HSTRY 32 POWPREF Win32  Feb 10 14:09:54 2005                                
    HSTRY 33 GENLES  Win32  Feb 10 14:10:00 2005 Sdsq= 0.210E+07 S/E=  37.8     
    HSTRY 34 EXPGUI 1.75 1.42 (34 changes) -- 02/10/05 14:11:51                 
    HSTRY 35 GENLES  Win32  Feb 10 14:11:56 2005 Sdsq= 0.199E+07 S/E=  5.82     
    HSTRY 36 GENLES  Win32  Feb 10 14:14:20 2005 Sdsq= 0.199E+07 S/E=  5.67     
    HSTRY 37 EXPEDT  Win32  Feb 10 14:15:44 2005                   F-EDT        
    HSTRY 38 EXPEDT  Win32  Feb 10 15:17:27 2005             L    P             
    HSTRY 39 GENLES  Win32  Feb 10 15:17:36 2005 Sdsq= 0.659E+08 S/E= 0.173     
    HSTRY 40 EXPGUI 1.75 1.42 (1 changes) -- 02/10/05 15:17:52                  
    HSTRY 41 GENLES  Win32  Feb 10 15:17:58 2005 Sdsq= 0.978E+07 S/E=  665.     
    HSTRY 42 GENLES  Win32  Feb 10 15:18:25 2005 Sdsq= 0.592E+07 S/E=  872.     
    HSTRY 43 GENLES  Win32  Feb 10 15:20:26 2005 Sdsq= 0.119E+08 S/E=  543.     
    HSTRY 44 EXPGUI 1.75 1.42 (66 changes) -- 02/11/05 12:52:15                 
    HSTRY 45 EXPTOOL  Win32  Feb 11 12:52:16 2005 P  A                          
    HSTRY 46 EXPGUI 1.75 1.42 (41 changes) -- 02/11/05 12:57:02                 
    HSTRY 47 EXPGUI 1.75 1.42 (16 changes) -- 02/11/05 12:58:50                 
    HSTRY 48 POWPREF Win32  Feb 11 12:59:10 2005                                
    HSTRY 49 GENLES  Win32  Feb 11 12:59:21 2005 Sdsq= 0.539E+10 S/E= 0.223E-02 
    HSTRY 50 GENLES  Win32  Feb 11 13:00:51 2005 Sdsq= 0.539E+10 S/E= 0.155E-03 
    HSTRY 51 EXPGUI 1.75 1.42 (66 changes) -- 02/11/05 15:55:16                 
    HSTRY 52 EXPTOOL  Win32  Feb 11 15:55:16 2005 P  A                          
    HSTRY 53 POWPREF Win32  Feb 11 15:55:27 2005                                
    HSTRY 54 GENLES  Win32  Feb 11 15:55:32 2005 Sdsq= 0.262E+09 S/E= 0.102     
    HSTRY 55 EXPGUI 1.75 1.42 (32 changes) -- 02/11/05 15:56:38                 
    HSTRY 56 GENLES  Win32  Feb 11 15:56:42 2005 Sdsq= 0.262E+09 S/E= 0.436E-01 
    HSTRY 57 EXPGUI 1.75 1.42 (16 changes) -- 02/11/05 15:57:40                 
    HSTRY 58 GENLES  Win32  Feb 11 15:57:44 2005 Sdsq= 0.262E+09 S/E= 0.432E-01 
    HSTRY 59 EXPGUI 1.75 1.42 (2 changes) -- 02/11/05 15:58:40                  
    HSTRY 60 GENLES  Win32  Feb 11 15:58:44 2005 Sdsq= 0.262E+09 S/E= 0.431E-01 
    HSTRY 61 EXPGUI 1.75 1.42 (3 changes) -- 02/11/05 16:14:43                  
    HSTRY 62 POWPREF Win32  Feb 11 16:14:44 2005                                
    HSTRY 63 GENLES  Win32  Feb 11 16:14:51 2005 Sdsq= 0.262E+09 S/E= 0.761     
    HSTRY 64 GENLES  Win32  Feb 21 11:17:26 2005 Sdsq= 0.262E+09 S/E= 0.704     
    HSTRY 65 GENLES  Win32  Mar 21 11:19:44 2005 Sdsq= 0.262E+09 S/E= 0.704     
    HSTRY 66 EXPEDT  Win32  Mar 21 11:23:01 2005                   F-EDT        
    HSTRY 67 EXPEDT  Win32  Mar 21 11:23:21 2005 File cleanup only              
    HSTRY 68 EXPEDT  Win32  Mar 21 11:28:07 2005                   F-EDT        
    HSTRY 69 EXPEDT  Win32  Mar 21 11:31:54 2005                   F-EDT        
    HSTRY 70 EXPEDT  Win32  Mar 21 11:33:18 2005                   F-EDT        
    HSTRY 71 EXPEDT  Win32  Mar 21 11:36:49 2005 File cleanup only              
    HSTRY 72 EXPEDT  Win32  Mar 21 11:38:19 2005                   F-EDT        
    HSTRY 73 EXPEDT  Win32  Mar 21 11:42:04 2005                   F-EDT        
    HSTRY 74 GENLES  Win32  May 18 14:55:00 2005 Sdsq= 0.262E+09 S/E= 0.704     
    HSTRY 75 EXPEDT  Win32  May 18 14:57:59 2005                   F-EDT        
    HSTRY 76 EXPEDT  Win32  May 18 15:02:19 2005                   F-EDT        
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  FOUR CDAT1  FCLC Z    1 NOPR  0.000                                           
  GNLS  RUN on May 18 14:55:02 2005    Total cycles run  79      0.26193E+09    
  GNLS CDAT1  MXCY  3                                                           
  GNLS SHFTS      0.84      0.08                                                
 AFAC  C     2.310020.8439 1.020010.2075 1.5886  .5687  .865051.6512  .2156 RHF 
 AFAC  C_    12.011 .6646       .0035                                           
 AFAC  C_SIZ      1.12      0.92 1.65    3                                      
 AFAC  C_XAB  288.3 170.4 84.13 10.67 7.054 52.30 141.0                         
 AFAC  C_XF1  0.036 0.027 0.018 0.003 0.002 0.049 0.024-0.001-0.001-0.001       
 AFAC  C_XF2  0.021 0.015 0.009 0.002 0.001 0.031 0.012 0.000 0.000 0.000       
 AFAC  N    12.2126  .0057 3.1322 9.8933 2.012528.9975 1.1663  .5826-11.529 RHF 
 AFAC  N_    14.007  .936        1.90                                           
 AFAC  N_SIZ      1.08      0.88 1.55    4 1.30                                 
 AFAC  N_XAB  568.1 337.1 166.1 18.37 11.06 1000. 272.0                         
 AFAC  N_XF1  0.061 0.046 0.031 0.006 0.003 0.081 0.040-0.002-0.002-0.002       
 AFAC  N_XF2  0.042 0.029 0.018 0.003 0.002 0.061 0.025 0.000 0.000 0.000       
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5803      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 EXPR  HTYP1  PXC  RSN  ANG  FLT                                                
 EXPR  NATYP    3                                                               
 EXPR  NHST     4                                                               
 EXPR ATYP 1  N           3      1.08      0.88 1.55    4 1.30                  
 EXPR ATYP 2  O           6      1.09      0.89 1.45   96 1.40                  
 EXPR ATYP 3  C          23      1.12      0.92 1.65    3                       
 EXPR DELFRL      5527                                                          
 EXPR FCLCRL      1887                                                          
 EXPR FOBSRL      3742                                                          
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 = 0.2388E+05 for   10 variables                     
 REFN RESTR      87 2.60591E+08                                                 
 REFN RPOWD     0.2364    0.1866  10893 1.34625E+06    0.0000    0.0000     0   
 REFN STATS  Cycle  79 There were 10980 observations. Total CHI**2 = 2.6193E+08 
CIF AUTHOR    Michal Husak                                                      
CRS1    PNAM  from F:/gsas/MyWork/MEMAL_monokrystal/Structure/ErgMalMonokrystal.
CRS1   NATOM   32                                                               
CRS1  ABC     5.711428 12.770694 33.152000    Y    0                            
CRS1  ABCSIG  0.002205  0.005615  0.017635                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG    0.0000    0.0000    0.0000                                      
CRS1  AT  1A  N         0.301900  0.303600  0.796000  1.000000N1         4 000  
CRS1  AT  1B  0.051929                                                    I  U  
CRS1  AT  2A  N        -0.291400  0.226100  0.646500  1.000000N2         4 000  
CRS1  AT  2B  0.051929                                                    I  U  
CRS1  AT  3A  N        -0.089600 -0.120900  0.585500  1.000000N3         4 000  
CRS1  AT  3B  0.051929                                                    I  U  
CRS1  AT  4A  O        -0.364300 -0.103400  0.626300  1.000000O4         4 000  
CRS1  AT  4B  0.051929                                                    I  U  
CRS1  AT  5A  O         0.264400 -0.239600  0.621700  1.000000O5         4 000  
CRS1  AT  5B  0.051929                                                    I  U  
CRS1  AT  6A  C         0.123100  0.357200  0.773600  1.000000C6         4 000  
CRS1  AT  6B  0.051929                                                    I  U  
CRS1  AT  7A  C         0.093900  0.327500  0.737800  1.000000C7         4 000  
CRS1  AT  7B  0.051929                                                    I  U  
CRS1  AT  8A  C        -0.076600  0.347100  0.702900  1.000000C8         4 000  
CRS1  AT  8B  0.051929                                                    I  U  
CRS1  AT  9A  C        -0.161000  0.224100  0.685300  1.000000C9         4 000  
CRS1  AT  9B  0.051929                                                    I  U  
CRS1  AT 10A  C        -0.328100  0.125200  0.625400  1.000000C10        4 000  
CRS1  AT 10B  0.051929                                                    I  U  
CRS1  AT 11A  C        -0.168400  0.046700  0.616700  1.000000C11        4 000  
CRS1  AT 11B  0.051929                                                    I  U  
CRS1  AT 12A  C        -0.046900  0.039700  0.651100  1.000000C12        4 000  
CRS1  AT 12B  0.051929                                                    I  U  
CRS1  AT 13A  C         0.001100  0.126300  0.679400  1.000000C13        4 000  
CRS1  AT 13B  0.051929                                                    I  U  
CRS1  AT 14A  C         0.194700  0.113000  0.723700  1.000000C14        4 000  
CRS1  AT 14B  0.051929                                                    I  U  
CRS1  AT 15A  C         0.333100  0.035800  0.732700  1.000000C15        4 000  
CRS1  AT 15B  0.051929                                                    I  U  
CRS1  AT 16A  C         0.502400  0.048200  0.763100  1.000000C16        4 000  
CRS1  AT 16B  0.051929                                                    I  U  
CRS1  AT 17A  C         0.501000  0.120200  0.794900  1.000000C17        4 000  
CRS1  AT 17B  0.051929                                                    I  U  
CRS1  AT 18A  C         0.328700  0.217700  0.784700  1.000000C18        4 000  
CRS1  AT 18B  0.051929                                                    I  U  
CRS1  AT 19A  C         0.202800  0.210400  0.752500  1.000000C19        4 000  
CRS1  AT 19B  0.051929                                                    I  U  
CRS1  AT 20A  C        -0.430100  0.322500  0.647700  1.000000C20        4 000  
CRS1  AT 20B  0.051929                                                    I  U  
CRS1  AT 21A  C        -0.219900 -0.053700  0.610100  1.000000C21        4 000  
CRS1  AT 21B  0.051929                                                    I  U  
CRS1  AT 22A  C        -0.089900 -0.231000  0.581100  1.000000C22        4 000  
CRS1  AT 22B  0.051929                                                    I  U  
CRS1  AT 23A  C        -0.238800 -0.294200  0.554200  1.000000C23        4 000  
CRS1  AT 23B  0.051929                                                    I  U  
CRS1  AT 24A  C         0.122700 -0.276000  0.593600  1.000000C24        4 000  
CRS1  AT 24B  0.051929                                                    I  U  
CRS1  AT 25A  O         0.585300  0.061700  0.510400  1.000000O101       4 000  
CRS1  AT 25B  0.051929                                                    I  U  
CRS1  AT 26A  O         0.296100  0.004100  0.549600  1.000000O102       4 000  
CRS1  AT 26B  0.051929                                                    I  U  
CRS1  AT 27A  O         0.466000  0.212100  0.400400  1.000000O103       4 000  
CRS1  AT 27B  0.051929                                                    I  U  
CRS1  AT 28A  O         0.641700  0.115600  0.453700  1.000000O104       4 000  
CRS1  AT 28B  0.051929                                                    I  U  
CRS1  AT 29A  C         0.355200  0.053600  0.518900  1.000000C105       4 000  
CRS1  AT 29B  0.051929                                                    I  U  
CRS1  AT 30A  C         0.213200  0.129600  0.500700  1.000000C106       4 000  
CRS1  AT 30B  0.051929                                                    I  U  
CRS1  AT 31A  C         0.268800  0.182200  0.464600  1.000000C107       4 000  
CRS1  AT 31B  0.051929                                                    I  U  
CRS1  AT 32A  C         0.454700  0.152900  0.437900  1.000000C108       4 000  
CRS1  AT 32B  0.051929                                                    I  U  
CRS1  CELVOL       2418.070          1.172                                      
CRS1  CHMF 1  N             3.00                                                
CRS1  CHMF 2  O             6.00                                                
CRS1  CHMF 3  C            23.00                                                
CRS1  FMHST1  1                                                                 
CRS1  FMPCTL   28   64  168    0    0    0   28   64   84                       
CRS1  SG SYM  P 21 21 21                                                        
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      3   19   0.00100     YYY YYNN                                   
HAP1 1PRCF 1   0.280036E+03  -0.153212E+02   0.802836E+00   0.000000E+00        
HAP1 1PRCF 2   0.183715E+01   0.000000E+00   0.547879E-02   0.500000E-03        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00                       
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  F:/gsas/MYWORK/METMAL/DATA/METMAL~1.RAW                           
HST  1  HNAM                                                                    
HST  1  IFIL  F:/gsas/MYWORK/INSTUM~1/BM01B.ins                                 
HST  1 BANK     1                                                               
HST  1 BIGFO   0.380810E+06                                                     
HST  1 CHANS         0         1     11590 105682048     11591    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR    0.6996    0.0000    0.0000               1.000    1     0.      
HST  1 ICONS    0.6996    0.0000    0.0000               1.000    0     0.      
HST  1 IRAD     0                                                               
HST  1 MAXRF  101                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF   667    1.3744    Y    Y                                           
HST  1 R-FAC  667   0.35354   8.553147E+06                                      
HST  1 RPOWD    0.2364    0.1866  10893 1.34625E+06    0.0000    0.0000    0    
HST  1 TRNGE   2.25750  29.48750                                                
HST  1 WREXP    0.0213                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     1   10    N    0    Y                                           
HST  1BAKGD1    1094.701763    -130.890916    -144.503976      90.502236        
HST  1BAKGD2     129.446074     -45.501754     126.701967     -49.791496        
HST  1BAKGD3     -28.838860      52.711895                                      
HST  1CHI       0.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  10.000E+000     2.255                                                
HST  1EXC  2    29.490  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1FFANS1  N            0.000     0.000   NN    0                            
HST  1FFANS2  O            0.000     0.000   NN    0                            
HST  1FFANS3  C            0.000     0.000   NN    0                            
HST  1HSCALE     39.894        Y    0                                           
HST  1I HEAD  ESRF BM01B profile wl 0.69956 2004                                
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1INAME   BM01B                                                             
HST  1MNREF     0    1.3744                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000    Y                                                     
HST  1PHI       0.0000                                                          
HST  1PRCF1     3   19   0.01000                                                
HST  1PRCF11       2.412430      -0.335344       0.256752  0.000000E+000        
HST  1PRCF12       0.689770       0.407357       0.002346       0.000506        
HST  1PRCF13  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF14  0.000000E+000  0.000000E+000  0.000000E+000  0.000000E+000        
HST  1PRCF15  0.000000E+000  0.000000E+000  0.000000E+000                       
HST  1TRMNMX   1.00000   1.00000                                                
HST  2  HNAM  Bond distance restraints                                          
HST  2 FACTR    1000.00                                                         
HST  2 NBNDS   34                                                               
HST  2 RMSD    34    0.1354                                                     
HST  2BD0001  1    1    6  1  0  0  0  0 1.387 0.010                            
HST  2BD0002  1    1   18  1  0  0  0  0 1.369 0.010                            
HST  2BD0003  1    2    9  1  0  0  0  0 1.507 0.010                            
HST  2BD0004  1    2   10  1  0  0  0  0 1.484 0.010                            
HST  2BD0005  1    2   20  1  0  0  0  0 1.472 0.010                            
HST  2BD0006  1    3   21  1  0  0  0  0 1.329 0.010                            
HST  2BD0007  1    3   22  1  0  0  0  0 1.445 0.010                            
HST  2BD0008  1    4   21  1  0  0  0  0 1.233 0.010                            
HST  2BD0009  1    5   24  1  0  0  0  0 1.360 0.010                            
HST  2BD000A  1    6    7  1  0  0  0  0 1.358 0.010                            
HST  2BD000B  1    7    8  1  0  0  0  0 1.488 0.010                            
HST  2BD000C  1    7   19  1  0  0  0  0 1.406 0.010                            
HST  2BD000D  1    8    9  1  0  0  0  0 1.531 0.010                            
HST  2BD000E  1    9   13  1  0  0  0  0 1.533 0.010                            
HST  2BD000F  1   10   11  1  0  0  0  0 1.506 0.010                            
HST  2BD0010  1   11   12  1  0  0  0  0 1.505 0.010                            
HST  2BD0011  1   11   21  1  0  0  0  0 1.519 0.010                            
HST  2BD0012  1   12   13  1  0  0  0  0 1.326 0.010                            
HST  2BD0013  1   13   14  1  0  0  0  0 1.476 0.010                            
HST  2BD0014  1   14   15  1  0  0  0  0 1.384 0.010                            
HST  2BD0015  1   14   19  1  0  0  0  0 1.391 0.010                            
HST  2BD0016  1   15   16  1  0  0  0  0 1.412 0.010                            
HST  2BD0017  1   16   17  1  0  0  0  0 1.358 0.010                            
HST  2BD0018  1   17   18  1  0  0  0  0 1.366 0.010                            
HST  2BD0019  1   18   19  1  0  0  0  0 1.413 0.010                            
HST  2BD001A  1   22   23  1  0  0  0  0 1.519 0.010                            
HST  2BD001B  1   22   24  1  0  0  0  0 1.500 0.010                            
HST  2BD001C  1   25   29  1  0  0  0  0 1.267 0.010                            
HST  2BD001D  1   26   29  1  0  0  0  0 1.224 0.010                            
HST  2BD001E  1   27   32  1  0  0  0  0 1.255 0.010                            
HST  2BD001F  1   28   32  1  0  0  0  0 1.261 0.010                            
HST  2BD0020  1   29   30  1  0  0  0  0 1.454 0.010                            
HST  2BD0021  1   30   31  1  0  0  0  0 1.314 0.010                            
HST  2BD0022  1   31   32  1  0  0  0  0 1.461 0.010                            
HST  3  HNAM  Bond angle restraints                                             
HST  3 FACTR    1000.00                                                         
HST  3 NANGS   48                                                               
HST  3 RMSD    48    8.0201                                                     
HST  3AN   1    1    3    109.00     20.00  0006  0001  0012                    
HST  3AN   2    1    3    111.00     20.00  0009  0002  000A                    
HST  3AN   3    1    3    112.90     20.00  0009  0002  0014                    
HST  3AN   4    1    3    109.80     20.00  000A  0002  0014                    
HST  3AN   5    1    3    125.20     20.00  0015  0003  0016                    
HST  3AN   6    1    3    109.80     20.00  0001  0006  0007                    
HST  3AN   7    1    3    134.60     20.00  0006  0007  0008                    
HST  3AN   8    1    3    106.30     20.00  0006  0007  0013                    
HST  3AN   9    1    3    118.80     20.00  0008  0007  0013                    
HST  3AN  10    1    3    109.70     20.00  0007  0008  0009                    
HST  3AN  11    1    3    110.00     20.00  0002  0009  0008                    
HST  3AN  12    1    3    108.70     20.00  0002  0009  000D                    
HST  3AN  13    1    3    115.30     20.00  0008  0009  000D                    
HST  3AN  14    1    3    111.70     20.00  0002  000A  000B                    
HST  3AN  15    1    3    110.80     20.00  000A  000B  000C                    
HST  3AN  16    1    3    110.80     20.00  000A  000B  0015                    
HST  3AN  17    1    3    106.60     20.00  000C  000B  0015                    
HST  3AN  18    1    3    125.40     20.00  000B  000C  000D                    
HST  3AN  19    1    3    121.20     20.00  0009  000D  000C                    
HST  3AN  20    1    3    116.10     20.00  0009  000D  000E                    
HST  3AN  21    1    3    122.60     20.00  000C  000D  000E                    
HST  3AN  22    1    3    128.30     20.00  000D  000E  000F                    
HST  3AN  23    1    3    115.70     20.00  000D  000E  0013                    
HST  3AN  24    1    3    116.00     20.00  000F  000E  0013                    
HST  3AN  25    1    3    120.30     20.00  000E  000F  0010                    
HST  3AN  26    1    3    122.60     20.00  000F  0010  0011                    
HST  3AN  27    1    3    118.70     20.00  0010  0011  0012                    
HST  3AN  28    1    3    134.70     20.00  0001  0012  0011                    
HST  3AN  29    1    3    106.10     20.00  0001  0012  0013                    
HST  3AN  30    1    3    119.20     20.00  0011  0012  0013                    
HST  3AN  31    1    3    127.90     20.00  0007  0013  000E                    
HST  3AN  32    1    3    108.80     20.00  0007  0013  0012                    
HST  3AN  33    1    3    123.20     20.00  000E  0013  0012                    
HST  3AN  34    1    3    122.90     20.00  0003  0015  0004                    
HST  3AN  35    1    3    115.20     20.00  0003  0015  000B                    
HST  3AN  36    1    3    121.70     20.00  0004  0015  000B                    
HST  3AN  37    1    3    111.30     20.00  0003  0016  0017                    
HST  3AN  38    1    3    110.90     20.00  0003  0016  0018                    
HST  3AN  39    1    3    108.80     20.00  0017  0016  0018                    
HST  3AN  40    1    3    117.90     20.00  0005  0018  0016                    
HST  3AN  41    1    3    119.90     20.00  0019  001D  001A                    
HST  3AN  42    1    3    119.70     20.00  0019  001D  001E                    
HST  3AN  43    1    3    120.40     20.00  001A  001D  001E                    
HST  3AN  44    1    3    131.20     20.00  001D  001E  001F                    
HST  3AN  45    1    3    130.70     20.00  001E  001F  0020                    
HST  3AN  46    1    3    122.10     20.00  001B  0020  001C                    
HST  3AN  47    1    3    118.20     20.00  001B  0020  001F                    
HST  3AN  48    1    3    119.40     20.00  001C  0020  001F                    
HST  4  HNAM  Planar group restraints                                           
HST  4 FACTR    100000.                                                         
HST  4 NPLNS    1                                                               
HST  4 RMSD     8    0.1783                                                     
HST  4PL   1    1    8 0.010019001A001B001C001D001E001F0020                     
LNCN   1   1  1ALLUISO  1.0000                                                  
ZZZZZZZZZZZZ  Last EXP file record                                              
