name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Testing
      run: cmake --version
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Extra setup
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-openblas mingw-w64-x86_64-perl msys2-w32api-runtime mingw-w64-x86_64-wxWidgets
    - name: More setup
      run: mkdir ci
    - name: Build
      working-directory: ci
      run: |
        dir D:\a\_temp\msys\\msys64\
        dir D:\a\_temp\msys\\msys64\mingw64\
        $env:Path = "D:\a\_temp\msys\\msys64\mingw64\bin;$env:Path"
        cmake .. -G"MinGW Makefiles" -DuseGUI=no -DMINGW=1 -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        mingw32-make

