name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-openblas mingw-w64-x86_64-cmake mingw-w64-x86_64-perl mingw-w64-x86_64-wxWidgets
    - name: Build
      working-directory: ci
      run: |
        cmake .. -G"""MinGW Makefiles""" -DuseGUI=no 
        mingw32-make -j2

