name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout crystals
      uses: actions/checkout@v1
    - name: Setup MSYS2 environment
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Install compiler and tools
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-openblas mingw-w64-x86_64-perl msys2-w32api-runtime mingw-w64-x86_64-wxWidgets
    - name: Create build folder
      run: mkdir ci
    - name: Build crystals
      working-directory: ci
      run: |
        $env:Path = "D:\a\_temp\msys\\msys64\mingw64\bin;$env:Path"
        cmake .. -G"MinGW Makefiles" -DuseGUI=no -DMINGW=1 -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        mingw32-make -j2
    - name: Test crystals
      working-directory: test_suite
      shell: cmd
      run: |
        mkdir script
        echo "%SCRIPT NONE" > script\\tipauto.scp
        echo "%END SCRIPT" >> script\\tipauto.scp
        set PATH=D:\a\_temp\msys\\msys64\mingw64\bin;%PATH%
        set CRYSDIR="..\ci\"
        set COMPCODE=MIN64
        perl testsuite.pl
