name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        cl: [gui, nogui]

    steps:
    - name: Checkout crystals
      uses: actions/checkout@v1
#
# WIN only
#
    - name: Setup MSYS2 environment
      uses: numworks/setup-msys2@v1
      if: matrix.os == 'windows-latest'
      with:
        msystem: MINGW64
# WIN ONLY
    - name: Install compiler and tools
      if: matrix.os == 'windows-latest'
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-openblas mingw-w64-x86_64-perl msys2-w32api-runtime mingw-w64-x86_64-curl
#
# Install wxWidgets - GUI only
#
    - name: Setup wxWidgets
      if: matrix.os == 'windows-latest' && matrix.cl == 'gui'
      shell: cmd
      run: |
        curl -LsS https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxMSW-3.1.3_gcc810_x64_Dev.7z > dev.7z
        curl -LsS https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3-headers.7z > head.7z
        7z x dev.7z -owx -y
        7z x head.7z -owx -y
        dir
#
    - name: Create build folder
      run: mkdir ci
#
# Build WIN / NOGUI
#
    - name: Build crystals
      working-directory: ci
      if: matrix.os == 'windows-latest' && matrix.cl == 'nogui'
      run: |
        $env:Path = "D:\a\_temp\msys\\msys64\mingw64\bin;$env:Path"
        cmake .. -G"MinGW Makefiles" -DuseGUI=no -DMINGW=1 -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        mingw32-make -j2
        del ..\test_suite\gui.tst
#
# Build WIN / GUI
#
    - name: Build crystals
      working-directory: ci
      if: matrix.os == 'windows-latest' && matrix.cl == 'gui'
      run: |
        $env:Path = "D:\a\_temp\msys\\msys64\mingw64\bin;$env:Path"
        cmake .. -G"MinGW Makefiles" -DuseGUI=yes -DMINGW=1 -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DwxWidgets_ROOT_DIR=..\wx -DwxWidgets_LIB_DIR=..\wx\lib\gcc810_x64_dll -DwxWidgets_CONFIGURATION=mswu & echo Try again
        cmake .. -G"MinGW Makefiles" -DuseGUI=yes -DMINGW=1 -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DwxWidgets_ROOT_DIR=..\wx -DwxWidgets_LIB_DIR=..\wx\lib\gcc810_x64_dll -DwxWidgets_CONFIGURATION=mswu
        mingw32-make -j2
#
    - name: Test crystals
      working-directory: test_suite
      if: matrix.os == 'windows-latest'
      shell: cmd
# Prevent interactive scripts from running
# Prevent gui test from running for this cl version
# Setup environment
# Compcode sets folder with reference test outputs
# Go
      run: |
        mkdir script
        set CRYSDIR=.\,..\ci\
        echo "%SCRIPT NONE" > script\\tipauto.scp
        echo "%END SCRIPT" >> script\\tipauto.scp
        echo "%SCRIPT NONE" > script\\guideauto.scp
        echo "%END SCRIPT" >> script\\guideauto.scp
        set PATH=D:\a\_temp\msys\\msys64\mingw64\bin;%PATH%
        set COMPCODE=MIN64GH
        perl testsuite.pl
#
# If failures, save the test outputs for later comparisons
    - name: Upload crystals test outputs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-outputs
        path: test_suite
