name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MSYS2
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-toolchain
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-gcc
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-make
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-openblas
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-cmake
    - run: msys2do pacman --noconfirm -S mingw-w64-x86_64-perl
    - run: |
        set MSYSTEM=MINGW64
        msys2do mkdir ci
        msys2do cd ci
        msys2do cmake .. -G"MinGW Makefiles" -DuseGUI=no 
        msys2do  mingw32-make -j2

